micronaut:
  application:
    name: apiMobileOpenid
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
        paths: classpath:META-INF/swagger
        mapping: /swaggerYAML/**
